### ISSUE TITLE
link contributors to bills

### ISSUE THREAD

**Issue by mscarey** [open-austin/influence-texas#1]
We discussed an idea to identify campaign contributors associated with particular bills by using Texas Ethics Commission data to find statistically unusual contributions to the bills' sponsors. We can also use the scraped Background and Purpose Statements for each bill (see issue #10). If we get access to the Texans for Public Justice industry categories for each donor, we could try using those as well.

Determining which contributions are actually statistically unusual may require resolving issue #9 (aggregate contributions for candidates and their SPACs) first.

The idea of identifying bill supporters by scraping the legislative witness lists might be relevant too, but it's probably not critical.

**Comment by lazarus1331** [comment]
Donations are not allowed during the session to prevent this type of behavior.  We will be looking at assigning industry tags to bills and legislator votes to determine if there is a correlation.
