### ISSUE TITLE
Determining what a bill actually does

### ISSUE THREAD

**Issue by AmyMcCullough** [open-austin/influence-texas#10]
How do we determine what a bill actually does?

The **caption** -- which is the "relating to..." sentence at the beginning of a bill -- can be helpful, but not necessarily.

The **Bill Analysis**, which is written by the Texas Lege Council (TLC) for every bill that gets a committee hearing (and thus every bill that passes) can be helpful, but not always.

The "**Background and Purpose Statements**" that always occur as the first paragraph of a Bill Analysis (and are labeled as such) can sometimes be more helpful. They are not written in legalese. They are written by the senator or representative (or whatever lobbyist drafted the bill and gave it to the senator or representative) and submitted to the Texas Lege Council (TLC) . TLC strips the grandstanding and erroneous factual claims out of them, editing them down to about two fairly vague sentences. But the two sentences can still give you a clue as to the reason the bill was proposed in the first place.

Thus, I think a scraping project -- and a data science project --- should be to **scrape the Background and Purpose Statements and factor in the use of that language when matching bills to campaign contributions.** (More work, I know. But this could really be valuable. I think it's worth it.)

**Comment by AmyMcCullough** [comment]
Here are some samples/examples.

Here is the Texas Legislature Online page for **HB 4**: http://www.capitol.state.tx.us/BillLookup/Text.aspx?LegSess=85R&Bill=HB4

If you open the House Committee Report version of the bill, you see the Caption at the top: 
**"relating to monetary assistance provided by the Department of Family and Protective Services to certain relative or designated caregivers; creating a criminal offense; creating a civil penalty."**

The Bill Analysis of HB 4 has the Background and Purpose (B&P) statement as the first paragraph: http://www.capitol.state.tx.us/tlodocs/85R/analysis/html/HB00004H.htm

**BACKGROUND AND PURPOSE** 
Interested parties note that children who are placed with certain relative or other designated caregivers have more stability and permanency in their lives and have better outcomes than children placed in non-relative caregiver or non-designated caregiver foster care. H.B. 4 seeks to improve outcomes by addressing the level of support for relative or other designated caregivers.
--
**Note:** The B&P contains the term "foster care" (the caption does not), which is a user-friendly/human-speak search term. Also, the B&P lets the reader know that the intent of the bill is to create more permanency when relocating foster kids, i.e. placing them with relatives or family friends. And it makes the "monetary assistance" reference in the caption make more sense, because the  B&P gives the impression that these relatives or family friends either haven't had access to the $ allotted to foster care parents who are not related to a child, or either they haven't had access to as much $ as unrelated foster care parents. However, the B&P doesn't say "money" or "monetary"; it says "level of support." Thus, it would be useful to use the captions and the B&Ps in scraping for search terms that indicate what a bill is actually doing (or at least what ii is _supposed_ to be doing, but that's another conversation).

FYI, something that is annoying is that **a Bill Analysis that comes from the Senate is formatted slightly differently than a Bill Analysis that comes from the House**. 

A **Senate Bill Analysi**s (for the Senate's version of HB 4 -- because a bill that originates in one chamber has to go to the other chamber for changes/approval in order for it to become a law): http://www.capitol.state.tx.us/tlodocs/85R/analysis/html/HB00004S.htm
The B&P content is still the first paragraph, but it is called **AUTHOR'S / SPONSOR'S STATEMENT OF INTENT** in a Senate Bill Analysis.

**Comment by mscarey** [comment]
I haven't done the data science part of this task, but I did scrape the Background and Purpose Statements. Since they're kind of big, I made them into a JSON and [put them on data.world](https://data.world/mcarey/texas-bill-analysis). The notebook I used is [here in the repo](https://github.com/open-austin/influence-texas/blob/master/notebooks/bill-analysis.ipynb).

**Comment by mscarey** [comment]
I think we can close this issue. The issue was to "scrape the Background and Purpose Statements and factor in the use of that language when matching bills to campaign contributions." The scraping part of that is done. The part about matching bills to campaign contributions refers back to issue #1.

**Comment by AmyMcCullough** [comment]
Gracias!
