### ISSUE TITLE
Replace openstates interface with pyopenstates

### ISSUE THREAD

**Issue by tonysyu** [open-austin/influence-texas#13]
I didn't realize that OpenStates has their own python SDK, `pyopenstates`, when I originally implemented the data dump from their API. It would be better to rely on OpenStates code for interfacing with their API.

**Comment by VictoriaODell** [comment]
Question that came up: How hard is it to pull more than the most recent session data? 
Need to figure that out prior to this

**Comment by lazarus1331** [comment]
This is still valid, but not a requirement for MVP.

**Comment by lazarus1331** [comment]
openstates new API is not compatible with this module anymore.
