### ISSUE TITLE
link amendment votes to amendment text

### ISSUE THREAD

**Issue by mscarey** [open-austin/influence-texas#14]
We could try linking each amendment (that was voted on, in the Open States data) to the specific text that was added or would have been added by that vote. Then we could use that information to create text annotations/visualizations showing which legislators supported which text in the bill.

This issue is a stretch because it would involve really difficult scraping/parsing of the Texas legislative journals.

For reference, the [@unitedstates](https://github.com/unitedstates/congressional-record) repo has a similar project that parses the federal Congressional Record. It seems more focused on extracting speeches, not amendment text (there are a few verbatim transcripts of conversations in the Texas journals, but not many).

**Comment by lazarus1331** [comment]
For design reasons, we are only displaying the final vote.  It is not currently feasible to show votes in real time, which would be the only reason this would make sense.   Vote.foundation is working on this, and we may partner with them in the future.
