### ISSUE TITLE
share bill and legislator data assets for collaboration

### ISSUE THREAD

**Issue by mscarey** [open-austin/influence-texas#15]
We should put our data someplace where we can add more content to it and load it to the website from there, rather than loading data directly from the Open States API into Django. I think data.world is the most likely option for bills and legislators. Once we add campaign finance data, our dataset might get too big for data.world, and it might become a privacy issue to store it there. Another option is to set up a server with a database for us to work in, but it could be challenging to keep track of the data transformation workflow if we do that. Or we could keep data here in the github repository.

**Comment by AmyMosley** [comment]
Decision resolved. Due to confidentiality issues and wishes of TPJ, TPJ info will not be housed on data.world.
