### ISSUE TITLE
Switch to production-quality web server (e.g. gunicorn, uwsgi) for main app

### ISSUE THREAD

**Issue by tonysyu** [open-austin/influence-texas#16]
The django dev-server is not meant for production deploys. [gunicorn](http://docs.gunicorn.org/en/stable/index.html) or [uwsgi](https://uwsgi-docs.readthedocs.io/en/latest/) are popular choices for serving up the webapp.

- [uwsgi example](https://www.stavros.io/posts/how-deploy-django-docker/)
- [gunicorn example](https://www.fir3net.com/Containers/Docker/how-to-configure-django-gunicorn-inside-a-docker-container.html)

**Comment by lazarus1331** [comment]
moving images to S3/cloudffront as well
