### ISSUE TITLE
Spot Check Open States API

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/influence-texas#21]
[The Open States API ](http://docs.openstates.org/en/latest/api/)is currently being used in this project and the team needs some help spot checking the data to see if it is correct. 

Currently, Texas is our main focus.

**Comment by VictoriaODell** [comment]
More info from @AmyMosley 

> See if all the bill’s on Chris’s important bills list will display via the OpenStates scraper/API: https://docs.google.com/spreadsheets/d/1Xyb0_kvu5ECxmNU8n1-EfUCJ42VaGFnYw03zWYx47Vs/edit#gid=0

We need to get Chris McConnell's bill list to get this started.

**Comment by mscarey** [comment]
I think our concerns about the OpenStates data basically boil down to this issue in the OpenStates repo: openstates/openstates#1782

**Comment by lazarus1331** [comment]
The Openstates data is not 100% accurate.  We need to double check the data against another source and find discrepancies.
