### ISSUE TITLE
Research other States Finance Data: Expansion of IFX

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/influence-texas#22]
Eventually, Influence Texas would like to expand and serve other states. One of the task to get this done is see how financial data is aggregated for other states. 

Ex: 
- Texas campaign finance data is housed by a non-profit in a private database that our group has access to.

**Comment by AmyMosley** [comment]
http://www.ncsl.org/research/elections-and-campaigns/disclosure-and-reporting-requirements.aspx

PROBLEM: This doesn't make groupings of states that use (if any) the same electronic reporting requirements. ARE THERE ANY THAT DO THE SAME THING? You can email the people listed as having made this NCSL page.

Most states now mandate that candidates report this information electronically. This process enables the lists of contributors to be posted automatically, giving concerned citizens access to the sources of campaign contributions. The Campaign Finance Institute maintains a list of every state reporting agency. To see state-specific reports, follow this link.

Various state entities that capture campaign finance reports -- and links to specific webpage within each agency:
http://www.cfinst.org/law/stateLinks.aspx

Disclosure and Reports of Contributions and Expenditures for Candidates

Though the reporting requirements and schedules vary, most states require disclosure of contributions (1) annually, (2) right before an election, and (3) soon after the election. Fourteen states require a candidate to disclose receipts of large contributions (typically more than $500 from a single source) within 24 hours. NCSL’s chart outlining state disclosure requirements provides the code sections to locate states’ individual reporting guidelines.

As an example, Mississippi Code Ann. § 23-15-807 provides disclosure guidelines for candidates for state office. During election years, candidates must file reports seven days before an election for which they have received contributions or made expenditures. They must also file periodic reports after April, May, June, September, and December of every gubernatorial election year, and an annual report the following January. Finally, if the candidate receives a contribution of $200 or more from a single source within 10 days of an election, the candidate must disclose it within 48 hours. The contents of these reports must include “the total amount of all contributions and the total amount of all expenditures of the candidate . . . during the election year.”

The amounts and dates will change across the states, but every one of them follows a similar pattern.

Disclosure and Reports of Independent Expenditures

U.S. Supreme Court rulings in Buckley v. Valeo and Citizens United v. Federal Election Commission protect independent political communications, like television or radio ads, as valid exercises of First Amendment free speech rights. This is based on the ruliing that the potential for corruption is not great enough with independent groups to warrant limiting their freedom of speech. This means that states are unable to limit how much an individual or group (such as a PAC) can raise if they are not directly associated with a campaign. States can require these groups to report where the money is going. Forty seven states require that groups or individuals report where their money is spent, with the timing of reports dependent on the amount of money spent and the proximity, in time, to the election. (For more information on the U.S. Supreme Court and Campaign Finance, see this link.)

As an example, Connecticut C.G.S.A. § 9-601d outlines reporting of independent expenditures for any person who makes independent expenditures of more than $1,000. They must disclose these reports to the state’s election commission on Jan. 10, April 10, July 10, Oct. 10, seven days before the election, and 30 days after any primary election.

NCSL has compiled a comprehensive outline of independent expenditure reporting for all 50 states.

Good chart -- contains state code sections: http://www.ncsl.org/Portals/1/documents/legismgt/elect/StateCampaignFinanceDisclosureRequirementsChart2015.pdf

**Comment by VictoriaODell** [comment]
It might be helpful to diagram out how we are currently handling our data so we can better visualize how the app can plug in with other databases.

**Comment by lazarus1331** [comment]
Outside the scope of this project for now.
