### ISSUE TITLE
Map TPJ industry and special interest categories to OpenStates/TLO subjects

### ISSUE THREAD

**Issue by jessvsmachine** [open-austin/influence-texas#24]
After determining the level of granularity for subjects, let's use card sorting to connect bill subjects to TPJ's industry and special interest categories

**Comment by jessvsmachine** [comment]
TPJ's interest tags:

- Unknown
- Agriculture
- Communications
- Computers & Electronics
- Construction
- Energy/Natural Resources/Waste
- Finance
- Health
- Ideological/Single Issue
- Insurance
- Labor
- Lawyers & Lobbyists
- Real Estate
- Transportation
- Miscellaneous Business
- Other

**Comment by mscarey** [comment]
Do we have a way to get the whole TPJ ontology? For instance, within the category "Computers & Electronics," TPJ has donors labeled as CM310 - Hardware, CM320 - Software, CM330 - Info Services, CM400 - Other Electronics, and so forth.

**Comment by jessvsmachine** [comment]
@mscarey Yep, I noticed that too. We're working on getting SQL permissions now and I'll update when we do.

**Comment by jessvsmachine** [comment]
TLO bill subject headings and index: https://docs.google.com/spreadsheets/d/1v4QUHrNZYJxpvjtr2G8nQvu5K8S3tpJ9u7zpEmsGLYE/edit?usp=sharing
