### ISSUE TITLE
Database/ App Comparison and Research  

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/influence-texas#35]
We need to review similar applications and see if this can help inform our data science and systems. here are a couple as found by @AmyMosley 

- Please check out https://maplight.org/. Where in the f*ck is their “secret sauce” documentation? FWIW, Amy is not overly impressed. 
- Please check out https://www.statedecoded.com/  Any ideas from this we can use?

**Comment by AmyMosley** [comment]
StateDecoded.com is trying to make laws/bills more understandable for non-lawyers. I am closing this issue and moving this task to the "WTF Does This Bill Do?" issue.
