### ISSUE TITLE
Review core contributor survey 

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/influence-texas#36]
Hey @AmyMosley I made a survey to help you better capture who is on your team and their availability/ commitment.

Please review asap and let me know if you would like to see any changes.  
https://docs.google.com/forms/d/e/1FAIpQLSf9ruLagmFwJvT08Bc2GrkQBcX53jrBtKJD7vOQFoFEkt_uHw/viewform?usp=sf_link

**Comment by AmyMosley** [comment]
Vickie. Looks great. I would remove the red asterisk next to phone number. It would be great to specify front or back-end dev, but it's fine the way it is.
Thanks!

**Comment by VictoriaODell** [comment]
@AmyMosley I updated it. Does it look okay now? 
https://goo.gl/forms/RVboe07elqmFO3h73

**Comment by VictoriaODell** [comment]
@jessvsmachine please also review and let me know if this works for ya'lls purposes.

**Comment by jessvsmachine** [comment]
@VictoriaODell Oh, I hadn't seen this! This is perfect :)
