### ISSUE TITLE
Create User_Persona.md

### ISSUE THREAD

**Issue by VictoriaODell** [open-austin/influence-texas#37]
## Overview of  Needs // Steps to take 
- [ ] Create Survey & identify list of potential users 
- [ ] Draft Personas based on survey results
- [ ] Approve personas with @AmyMosley 
- [ ] Create draft Users_Persona.md in google drive
- [ ] Publish users-persona.md in the repo. 
- [ ] Link users_persona.md  in contributor.md

*** recommended but not definite. This is just my own suggestion of the steps. Referring to @jessvsmachine on this.  

----
### Background 

The below is going to be in our contributor.md. We don't have a user_personas.md right now though. Defining these will help prioritize product development and help people better understand the use cases. 

> USER PERSONAS
> Please read this user personas document (USER_PERSONAS.md). Everything we do is for the user. So remember to keep them in mind at all times!

**Comment by AmyMosley** [comment]
I just uploaded a user personas doc to the folder in drive.

**Comment by jessvsmachine** [comment]
Jami distilled our whiteboarding to this doc https://docs.google.com/spreadsheets/d/1ktJRekokbAL_74sKJ44zSQ7M0ynoBs22bdpYSkwBcWY/edit#gid=0
