### ISSUE TITLE
Competitive UI/UX survey

### ISSUE THREAD

**Issue by jessvsmachine** [open-austin/influence-texas#40]
Create a folder of screenshots from political sites such as Open States, Open Secrets, Follow the Money, and any other sites dealing with legislator profiles and bill analysis. These shots will be mostly a reference for structure, tag usage, and common features.

Presuming the above will not be goldmine of inspiring UI, we can then move on to gathering shots from non-political, apps that might have similar structures and use Material design for more aesthetic inspiration (e.g. Another app might have a nice interaction for saving different topics to a watchlist).

**Comment by rickmcdux** [comment]
Screenshot folder is [here](https://drive.google.com/drive/u/0/folders/0Bz1EnpzcpEu2TDEwZ0xxT1dSWkE).
Wiki page of InfluenceTX-related links is [here](https://github.com/open-austin/influence-texas/wiki/Helpful-Links-for-ITX).

**Comment by rickmcdux** [comment]
Screenshot folder has been moved [here](https://github.com/open-austin/influence-texas/tree/master/images/screenshots/).

**Comment by lazarus1331** [comment]
This was completed.
