### ISSUE TITLE
Assess current designs and flow

### ISSUE THREAD

**Issue by jessvsmachine** [open-austin/influence-texas#47]
One or several people can complete this task, which is perfect for people without context. Visit this clickable prototype, click around, and tell us what you think. What additional features or information would you expect that you don't see? We know there are some missing pieces, and we'd love someone with fresh eyes to help us determine what they are.

Prototype here: https://iz042s.axshare.com/#g=4&p=home
PASSWORD is "influence"

Use the Discuss feature in the left menu to leave comments on areas that confused you or need improvement.

**Comment by jessvsmachine** [comment]
This is in progress. Added Rick and will add Arlin if/when she registers.

**Comment by Almaincognito** [comment]
It's looking quite nice. I don't know if this idea is germane to anyone else, and I know too well that aesthetics should preclude it but as I saw the opening graphic of Influence over our State, I couldn't help but think of how such a state looks now, as gerrymandered... In other words, the projected 2020 map, drawn to scale with voting blocks, influence of those blocks, and in what areas. 

I hate that I a getting a daemon bringing up the page I'm thinking of, but I suppose I am saying a) Would that image work as a jarring yesanding of the notion of influence? b} if not, no worries, but could you send me a working linky dinky doo

**Comment by rickmcdux** [comment]
I think you are referring to the [About](https://iz042s.axshare.com/#g=1&p=about_page) page. The prototype links are working for me.
