### ISSUE TITLE
Find resource for Lege bill subject assignments

### ISSUE THREAD

**Issue by AmyMosley** [open-austin/influence-texas#49]
Texas Legislature Online assigns bill subjects to bills. Method is unclear. Lege source/contact is needed. Possibly in Texas Lege Council IT dept.

**Comment by gilbertslade** [comment]
See here:
https://github.com/openstates/openstates/blob/master/openstates/tx/bills.py
Subjects are added on line 154, looking through to see where they're pruned.

**Comment by gilbertslade** [comment]
They're using a scraper called Pupa:
https://github.com/opencivicdata/pupa/tree/master/pupa

**Comment by gilbertslade** [comment]
Might also be using Billy.

**Comment by AmyMosley** [comment]
Will contact TLC to see who creates these subjects internally.
http://www.tlc.state.tx.us/contact
Contact Information
Phone Number
(512) 463-1155

Media Inquiries
Kimberly Shields
Public Information Officer
(512) 463-1151

Mailing Address
P.O. Box 12128
Austin, Texas 78711-2128

**Public Information Requests
(512) 463-1151
PIR Web Form**

**Comment by lazarus1331** [comment]
this was completed by @AmyMosley
