### ISSUE TITLE
Front end design

### ISSUE THREAD

**Issue by jessvsmachine** [open-austin/influence-texas#5]
Influence TX’s user experience adheres to guidelines, specs, and interaction patterns from [Google’s Material style](http://material.io). Using a standardized, research-backed design language allows designers and developers to use ready-made design libraries and development frameworks with shared, built-in specs. For those unfamiliar with Material, here is an introduction, which includes links to Material libraries for a number of design tools and development frameworks: https://designshack.net/articles/ux-design/google-material-design-everything-you-need-to-know/

Clickable Axure prototype:
http://iz042s.axshare.com
pw: influence

Bootstrap Material theme:
http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html

Material palette I used is the Indigo palette here: https://material.io/guidelines/style/color.html#color-color-palette

Obviously, this design is mobile-first, but the code should be responsive. For desktop, I'd say we can use a centered container around 40% wide with a max width of 1280 px.

SCREEN NOTES
Home Screen
- I will upload a png of the Influence TX logo

Senator and Bill Landing Pages
- I used Material's two-line list for these. I only made senators searchable because the bill list will be so limited, but I think we can do search for both.
- In the Bootstrap theme, the tile I used for senators was Tile with avatar 
(https://material.io/guidelines/components/lists.html#lists-specs)

Senator Profile Page
- For the xs mobile breakpoint, Votes and Donors should stack. For desktop breakpoints, they can be side-by-side 50s.

![home](https://user-images.githubusercontent.com/29525168/31253012-c44655ec-a9e8-11e7-8f3e-8d16a01d3303.png)
![about_page](https://user-images.githubusercontent.com/29525168/31253011-c4281154-a9e8-11e7-9127-f5ae2c4aff6e.png)
![news_page](https://user-images.githubusercontent.com/29525168/31253018-c47a3aba-a9e8-11e7-84e0-2a23143916b7.png)
![senator_detail](https://user-images.githubusercontent.com/29525168/31253015-c45177e2-a9e8-11e7-814c-c0382df33f88.png)
![senators_landing__1_](https://user-images.githubusercontent.com/29525168/31253016-c474c86e-a9e8-11e7-840f-bc29d448334d.png)
![bills_landing](https://user-images.githubusercontent.com/29525168/31253017-c4797332-a9e8-11e7-86fa-eecba3e41d72.png)
![bill_detail_sb11](https://user-images.githubusercontent.com/29525168/31253013-c44676bc-a9e8-11e7-821e-ac24d6dee01c.png)
![bill_detail](https://user-images.githubusercontent.com/29525168/31253014-c446b0b4-a9e8-11e7-97da-cc4e605117bc.png)

**Comment by tonysyu** [comment]
I'm not sure exactly what the "help wanted" tag is meant for in this task, but in my mind, the most important next step is to get someone who is comfortable digging into the templates that already exist, hooking up the bootstrap-material theme (or some equivalent theme), and making the tweaks necessary to match the mocks up and ensure responsiveness.
