### ISSUE TITLE
Contacting OpenStates for info on assignment of subjects to bills

### ISSUE THREAD

**Issue by AmyMosley** [open-austin/influence-texas#55]
Sharon will have contact info.

**Comment by AmyMosley** [comment]
When you contact OpenStates, you could try James Turk. https://github.com/jamesturk He's the person who merged Sharon's pull request. I would just ask if he could give us the code that Open States uses to assign subjects to Texas bills. You could tell him we looked for it on Github but we weren't able to find it, and say we're curious to see it because we want to make sure it's valid for the kind of campaign finance analysis we want to do.

**Comment by AmyMosley** [comment]
Emailed James on Feb. 3, 2018.

**Comment by AmyMosley** [comment]
How to join Open States Slack group:
http://openstates-slack.herokuapp.com/

handy point of reference for asking for help in the Slack group:
https://github.com/openstates/openstates/blob/master/openstates/tx/bills.py#L153 

OpenStates scraper disabled temporarily due to special session:
https://github.com/openstates/openstates/commit/e0f284d59d31b9e8329800d2c0a5f71cd42d2a73

**Comment by lazarus1331** [comment]
this was completed by @AmyMosley
