### ISSUE TITLE
Import OpenStates to integration database

### ISSUE THREAD

**Issue by lazarus1331** [open-austin/influence-texas#63]
The openstates data can be downloaded per state:
https://openstates.org/downloads/

We should import the Texas database into our integration database, so we can start looking at it and doing more development work.

**Comment by mscarey** [comment]
One way to do this would be to get the TX JSON download from https://openstates.org/downloads/, take all the fields except "actions" from the bills files, and all the fields from the legislators files. I don't really know how to create the instructions that would load that into the integration database.

**Comment by lazarus1331** [comment]
This works, except for vote data doesn't get imported for some reason.

**Comment by lazarus1331** [comment]
done.
