### ISSUE TITLE
Examine the openstates data for required data to achieve product goals

### ISSUE THREAD

**Issue by lazarus1331** [open-austin/influence-texas#64]
Determine what data will be required in a table or view that will provide the data required to accomplish the initial product goals.

Goals:
* record final floor votes from Texas Senators
* record industry for bill

**Comment by mscarey** [comment]
This [notebook](https://github.com/open-austin/influence-texas/blob/master/notebooks/import-bill-votes.ipynb) should cut out the unwanted parts of the OpenStates bill data. It outputs JSON.
