### ISSUE TITLE
TEC database 101

### ISSUE THREAD

**Issue by AmyMosley** [open-austin/influence-texas#7]
Candidates (including incumbent candidates, aka officeholders) for statewide office in Texas are required to file records of their campaign contributions and campaign expenditures with the **Texas Ethics Commission (TEC).* The general consensus is that candidates comply with the TEC's contribution filing requirements, because they don't want to run into problems -- like getting fined $10,000 by TEC when their political rival calls them out on a failure to report. More often, they get in trouble for how they spend the campaign funds (example: Dawna Dukes).
In Texas:

- There are no contribution $ limits for individuals

- There are no contribution $ limits for corporations

- There is a rule that prevents corporations from donating directly to candidates. Thus, they must donate through PACs (political action committees). (The exception to this rule is "Direct Campaign Expenditures," or DCEs. This is where a corporation can spend money on yard signs, TV advertisements, etc., as long as it is not coordinated directly with the candidate.)

- 501(c)4s are nonprofits that can engage in a certain amount of political activity; they do not have to disclose their donors. (Money from these groups is called "dark money.") In Texas, however, a 501(c)4 _might_ have to register as a PAC, if, under Texas law, it meets the definition of a PAC. 

- There are General-Purpose Political Committees (GPACs or MPACs) and Specific-Purpose Political Committees (SPACs). Candidates or Officeholders (COHs) will usually raise money under their name or under a SPAC that exists specifically for them. See "Filer-type-decoded" document below.

**This pdf shows you where to go to get the CSV files/campaign finance database:**
[zip-file-location.pdf](https://github.com/open-austin/influence-texas/files/1146583/zip-file-location.pdf)

**This amazing work of technical documentation will show you which CSVs you should care about and which ones for our purposes you can skip over:**
[zip-files.pdf](https://github.com/open-austin/influence-texas/files/1146678/zip-files.pdf)

**You should read the "ReadMe.txt" document within the zip file, which explains what is contained in Records #1-16. The record types we will use (in order of appearance in zip file) are: Record #2 (cand.csv), Record #3 (contribs_##.csv), Record #4 (cover.csv), Record #11 (filers.csv), Record #13 (loans.csv), Record #6 (purpose.csv), Record #15 (spacs.csv), and Record #16 (travel.csv).**
 
**This Filer-type-decoded document explains what the acronyms for filer types within the TEC database mean**
[Filer-type-decoded.docx](https://github.com/open-austin/influence-texas/files/1146578/Filer-type-decoded.docx)

Filers (candidates and officeholders and PACs) who file contribution and expenditure reports with TEC are assigned unique ID numbers within the TEC database. No other entities (contributors, for example) are assigned ID numbers.

**Comment by AmyMcCullough** [comment]
**Active PAC filer ID #s**. We need these, because the TEC database contains dead/inactive PACs. 

This TEC link has an **Excel file** on it that contains a list of active PACs that it says is "**updated daily**": https://www.ethics.state.tx.us/dfs/paclists.htm
![screen shot 2017-07-13 at 10 33 16 pm](https://user-images.githubusercontent.com/7925190/28197396-3cac1292-681c-11e7-96f5-ea126a2b9e94.png)
This is the list from July 13, 2017:
[Active-PACs-071317.nopag.xlsx](https://github.com/open-austin/influence-texas/files/1147267/Active-PACs-071317.nopag.xlsx)

**Comment by AmyMcCullough** [comment]
Date Range.

What date range should we select for contributors/contributions? We could go back a couple years... Or just keep it to 2016 and 2017. The TEC webpage says "Data as of 3/22/2017," which I interpret to mean "last updated March 22, 2017."
![screen shot 2017-07-14 at 12 02 42 am](https://user-images.githubusercontent.com/7925190/28198986-e2c2280a-6827-11e7-82f5-5719b6fb981d.png)

**Comment by AmyMcCullough** [comment]
**Senator Filer ID #s.** I'm compiling a list of these by hand -- as in typing in names of the 31 Senators here [](https://www.ethics.state.tx.us/Jasper/SimpleSearch.html ) and making an Excel list. I called the TEC help line and inquired about a master list of Filer ID #s for candidates/officeholders. They don't seem to have one. :(

**Comment by AmyMcCullough** [comment]
**Record #3 Contributions CSV**. The most important columns are highlighted in yellow. There are a lot of blank fields. I think we can kill most of them.
Main needs: TEC Form, Report Date, Filer ID#, Filer Type, Filer Name, Contribution $ amount, Individual Name, or Entity Name, City, State, Zip, Employer, Job Title.
[Record3-contributions.pdf](https://github.com/open-austin/influence-texas/files/1149020/Record3-contributions.pdf)

**Comment by AmyMcCullough** [comment]
Democratic Party chair's take on King Street Patriots' lawsuit:
https://www.tribtalk.org/2017/07/27/dark-money-darker-politics/
**Dark money, darker politics**

> Imagine if nothing prevented the Republican Party from setting up Texas Republicans, Inc., a corporation to shield billionaire donors and hide campaign activity. It is a conservative hack’s dream: Think Citizens United on steroids.
> 
> What if they launched a corporation for campaigns to outsource activities and avoid all Texas political disclosure requirements? Let’s say you’re a candidate who needs a nasty mail piece against your opponent, but you don’t want to take the heat for running a negative campaign. Or you want someone to intimidate voters at the polls to stomp out opposition, but you’re worried about that stain of voter suppression getting on your campaign. Discrimination doesn’t clean up so easily. In this dark money dreamland, there would be no disclosures, no limits and no state ban on corporate contributions to political campaigns.
> 
> The King Street Patriots attempted to make the dark money dream a reality when they raised a constitutional challenge to Texas’ restriction on corporate contributions and the legal definitions of political committees, campaign contributions and political contributions.
> 
> Fortunately, conservative dark money dreams were destroyed by the Texas Democratic Party’s victory. Before the Texas Supreme Court, the Texas Democratic Party prevailed over the architect behind Trump’s debunked massive voter fraud claim and her Houston-area Tea Party group were represented by the same lawyer behind Citizens United. The case was King Street Patriots, et al. v. Texas Democratic Party, et al.
> 
> That’s right, the architects behind Citizens United and Trump’s voter-fraud myth teamed up to create a legal environment in Texas where unlimited dark money could fund voter intimidation efforts.
> 
> Here’s how the Jim-Crow-style voter intimidation scheme worked. Back in 2010, the King Street Patriots and True the Vote trained poll watchers to harass voters who did not support their candidates — far-right Tea Party Republicans. King Street Patriots conducted forums to help promote select Republican candidates and advertised conservative materials for the benefit of Republican candidates.
> 
> The Tea Party group claimed it was purely a nonprofit and therefore exempt from Texas’ political disclosure laws. We didn’t buy it. Recognizing the threat of dark money, Texas Democrats sued the King Street Patriots under for failing to register as a political action committee, unlawfully accepting political contributions and making political expenditures....

**Comment by EvanCarroll** [comment]
This isn't linked to a PR, so I'm not sure where you left off on this. But I've created a PostgreSQL AGPL importer you're welcome to use. It imports the entirety of the TEC dataset including

* Campaign contribution dataset
* Lobby reports
* 1295 Forms 

https://github.com/EvanCarroll/db-Texas-Ethics-Commission
