### ISSUE TITLE
Run dedupe on Texas Ethics Commission data

### ISSUE THREAD

**Issue by mscarey** [open-austin/influence-texas#77]
We should use the [dedupe Python library](https://github.com/dedupeio/dedupe) to do record linkage on the campaign contributor records available from the [Texas Ethics Commission](https://www.ethics.state.tx.us/dfs/search_CF.htm). We need unique IDs for contributors. Because there are so many records, they probably need to be loaded into a database first. There's an annotated example about how to solve a very similar problem: [using dedupe on a MySQL database of Illinois political campaign contributions](https://dedupeio.github.io/dedupe-examples/docs/mysql_example.html).

Note that the TEC data already has unique IDs for recipients of contributions. In the TEC data, it's the "filerIdent" column in filers.csv and the contribs_**.csv files.

**Comment by EvanCarroll** [comment]
Where are the dupes? Can you provide an example?

**Comment by mscarey** [comment]
@EvanCarroll If you download the records from the "Text (CSV) Files" link on the TEC website, there's a file called contribs_01.csv. An example of a person whose name appears on multiple rows (without a unique ID) would be "ANDERSON, JOHN".

**Comment by lazarus1331** [comment]
We are using TPJ as the source of data, which performs dedupes on their imports already.  If we end up needing to use TEC data directly, then we can re-visit this.

**Comment by EvanCarroll** [comment]
What is TPJ? Could you expand that?

**Comment by EvanCarroll** [comment]
tpj
