### ISSUE TITLE
Estimate affinity between candidates and bills

### ISSUE THREAD

**Issue by mscarey** [open-austin/influence-texas#79]
We should look at whether we can estimate whether certain candidates/legislators would have supported bills that came up during sessions when they weren't in the legislature. If we could identify voting tendencies of clusters of legislators who get contributions from the same sources, then maybe we could (automatically) draw conclusions about how candidates would vote even before they get elected.

**Comment by lazarus1331** [comment]
We need to overcome the hurdle of getting the information to do this correlation.  We should focus on that first.  Closing this for now.
