### ISSUE TITLE
aggregate contributions for candidates and their SPACs

### ISSUE THREAD

**Issue by mscarey** [open-austin/influence-texas#9]
Some candidates collect contributions as CoH (candidate or officeholder) and others collect through SPACs (Specific issue Political Action Committees). Users will be interested in the sum of contributions through both methods.

[Texans for Public Justice](http://www.tpj.org/) has already done some of the work for linking SPACs to candidates.

**Comment by AmyMosley** [comment]
TPJ consolidates these in their system.
